create table signon 
(USERID VARCHAR(20) not null, 
USERPASSWORD VARCHAR(40),
EMAILID VARCHAR(255),
REGISTRATIONDT DATE,
LOGONDT DATE,
USERTYPE INTEGER NOT NULL,
PROFILEID INTEGER,
ZIPCODE VARCHAR(10),
STATUS VARCHAR(2),
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50)
)